language: "python"
python:
    - "3.6.8"
before_install:
    - pip install poetry
install:
    - poetry install
env:
    - FLASK_APP="run.py" DATABASE_URL="postgres://localhost/rb_landing" TEST_DATABASE_URL="postgres://localhost/test_rb_landing" APP_SETTINGS="development"
services:
    - postgresql
before_script:
    - psql -c 'create database test_rb_landing' -U postgres
    - psql test_rb_landing -U postgres < app/schema.sql
script:
    - poetry run isort **/*.py -c -vb
    - poetry run black . --check
    - poetry run make test
