language: "python"
python:
    - "3.7.4"
install:
    - pip install -r requirements.txt
env:
    - FLASK_APP="run.py" DATABASE_URL="postgres://localhost/test_database" APP_SETTINGS="development"
services:
    - postgresql
before_script:
    - psql -c 'create database test_database' -U postgres
    - psql test_database -U postgres < app/schema.sql
script:
    - black . --check
    - make test
